import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
// import { Geist, Geist_Mono } from "next/font/google"; import fonts here
import "./globals.css";
import NavBar from "@/components/NavBar";

export const metadata: Metadata = {
	title: "DEMO - Re:Fit Gym",
	description: "Generated by create next app",
};

const dmSans = DM_Sans({
	variable: "--font-primary",
	subsets: ["latin"],
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={`${dmSans.variable} font-primary`}>
			<body className={`max-w-7xl mx-4 mt-5 lg:mx-auto antialiased`}>
				<main>
					<NavBar />

					{children}
				</main>
			</body>
		</html>
	);
}
